### ISSUE TITLE
Making this as a generic node library & create a grunt task using it

### ISSUE THREAD

**Issue by MoOx** [sapegin/grunt-webfont#89]
I'm trying gulp right now, & the idea I have in mind is not to fork & modify grunt-webfont to create gulp-webfont.
@sapegin what do you think about creating a `node-svg2webfont` package that can be reused for this task or without grunt ?

* [x] Remove Grunt API calls from font generation code.
* [x] Remove Grunt API calls from font tests.
* [ ] Move as much code as possible to (kinda) `lib` folder.
* [ ] Create `webfont` node module, move code there and use it here as dependency.

**Comment by MoOx** [comment]
Closing due to inactivity.

**Comment by Soullivaneuh** [comment]
@sapegin gulp-iconfont is great, but does not provide all the options you provide like custom template for example.

Any chance to re-consider this issue? Thanks.

**Comment by sapegin** [comment]
@Soullivaneuh This project is not actively maintained for a long time since I don’t use neither Grunt nor icon fonts. If you want to extract the core logic and maintain it as a separate project please do it ;-)
